### ISSUE TITLE
Publish to Chrome Web Store

### ISSUE THREAD

**Issue by nwtgck** [syunm1n/color-aws-frame#1]
Hi, @miztch, thank you very much for your awesome project!

Could you package and publish it to [Chrome Web Store](https://chrome.google.com/webstore/category/extensions)?
I'd like to use and **sync it on my all chrome browsers** on different PCs.

**Comment by miztch** [comment]
Hi, @nwtgck. thanks for your issue-opening, and sorry for my late reply.
I'd like to tackle it so please wait a moment 😤

**Comment by nwtgck** [comment]
@miztch, I'm looking forward your app in Chrome Web Store!

**Comment by miztch** [comment]
Thanks for your paitience @nwtgck , I've finally finished publishing my chrome extension.
Check it out on Chrome Web Store 😉 
https://chrome.google.com/webstore/detail/colorawsframe/egnkjmppojiamgimoclpjopdohjejbjf

**Comment by nwtgck** [comment]
Thank you very much for your release. I installed it just now!
